function(lx_set_project_warnings target)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        set(lx_warnings -Wall -Wextra -Wpedantic -Wshadow)
        if(LX_WARNINGS_AS_ERRORS)
            list(APPEND lx_warnings -Werror)
        endif()
        target_compile_options(${target} INTERFACE ${lx_warnings})
    elseif(MSVC)
        target_compile_options(${target} INTERFACE /W4)
        if(LX_WARNINGS_AS_ERRORS)
            target_compile_options(${target} INTERFACE /WX)
        endif()
    endif()
endfunction()

