function(lx_enable_sanitizers target)
    if(NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        if(LX_ENABLE_ASAN OR LX_ENABLE_UBSAN OR LX_ENABLE_TSAN)
            message(FATAL_ERROR "Configured sanitizers require GCC or Clang")
        endif()
        return()
    endif()

    set(lx_sanitizers "")
    if(LX_ENABLE_ASAN AND LX_ENABLE_TSAN)
        message(FATAL_ERROR "AddressSanitizer and ThreadSanitizer cannot be combined")
    endif()
    if(LX_ENABLE_ASAN)
        list(APPEND lx_sanitizers address)
    endif()
    if(LX_ENABLE_UBSAN)
        list(APPEND lx_sanitizers undefined)
    endif()
    if(LX_ENABLE_TSAN)
        list(APPEND lx_sanitizers thread)
    endif()

    if(lx_sanitizers)
        list(JOIN lx_sanitizers "," lx_sanitizer_flags)
        target_compile_options(
            ${target}
            PRIVATE -fsanitize=${lx_sanitizer_flags} -fno-omit-frame-pointer
        )
        target_link_options(${target} PRIVATE -fsanitize=${lx_sanitizer_flags})
    endif()
endfunction()
